### PR TITLE
feat: parse dates in alert payload

### PR DESCRIPTION
**Pull request by antoinerabany**
Hi,

You did a nice job there !

We are using it within our organisation but as I wanted to use the dates in the alert, so I figured it needed a little parsing. Hope you will like it.

Thanks,

### CODE REVIEW

**Comment by julb** [comment]
Hello @antoinerabany, thanks for your contribution.

As some users may already use these values, could you create an alias value for the field name. 
Something like that :
`alert[f'${field}DateTime'] = datetime.fromisoformat(alert[field])`

Thanks for your contribution!

**Comment by antoinerabany** [comment]
You're right, I implemented your fix. 

Thanks for the feedback.

**Comment by julb** [comment]
Hello @antoinerabany, thanks again for the change.

I did some testing and unfortunately, AlertManager sends date in the following RFC3339 format such as `2021-01-01T00:00:00.00000000Z`.

The thing is `datetime.fromisoformat` does not support such date times.
I found that the iso8601 package supports such format: https://pypi.org/project/iso8601/
May I request you to:
- replace `from datetime import datetime` to `import iso8601`
- replace `datetime.fromisoformat(...)` per `iso8601.parse_date(...)`
- add `iso8601==0.1.14` dependency in `setup.py`

Note: the output seems to look like: '2021-01-01 00:00:00.000000+00:00' in the template (the timezone is appended).

Thanks a lot for your time.

**Comment by antoinerabany** [comment]
Sorry about that, I did as you asked.

Thanks

**Comment by julb** [comment]
Thanks @antoinerabany for your contribution.
I will release it today.

**Pull request merged**
